# Generated by Django 4.2.11 on 2024-10-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standarduser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español")],
                default="es",
                max_length=30,
            ),
        ),
    ]
